---
- name: Ensure lidarr directories exist with proper permissions
  file:
    path: "{{ lidarr_compose_dir }}"
    state: directory
    mode: "0755"
    owner: "catguru"
    group: "catguru"
    recurse: true
  loop:
    - { path: "{{ lidarr_config_dir }}" }
    - { path: "{{ lidarr_data_dir }}" }

- name: Deploy lidarr Docker Compose file
  template:
    src: lidarr-compose.yml.j2
    dest: "{{ lidarr_compose_path }}"
  notify: 
    - Restart lidarr

- name: Launch lidarr using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ lidarr_compose_dir }}"
    files:
      - "{{ lidarr_compose_path }}"
    state: present
