---
# Check if docker-compose is already installed
- name: Check if docker-compose is already installed
  ansible.builtin.command:
    cmd: docker-compose --version  # Check if docker-compose is installed by running the version command
  register: docker_compose_check   # Register the result of the command
  failed_when: false               # Do not fail if docker-compose is not installed
  changed_when: false              # Do not mark the task as changed

# Ensure docker-compose is installed (if not already installed)
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present
  when: docker_compose_check.rc is not defined or docker_compose_check.rc != 0  # Only run if docker-compose is not installed

# Check if Docker service is running
- name: Check if Docker service is running
  ansible.builtin.service_facts:  # Gather facts about the services running on the target machine

# Ensure Docker service is running (if not already running)
- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: "'docker' not in ansible_facts.services or ansible_facts.services['docker'].state != 'running'"  # Only run if Docker is not running

# Setup Sonarr directory
- name: Setup Sonarr directory
  ansible.builtin.file:
    path: "{{ sonarr_compose_dir }}"
    state: directory
    mode: '0755'  # Optional file permissions
    owner: catguru  # Optional ownership
    group: catguru  # Optional group ownership

# Deploy Sonarr using Docker Compose
- name: Deploy Sonarr using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "{{ sonarr_compose_path }}"
    mode: '0755'  # Optional file permissions
    owner: catguru  # Optional ownership
    group: catguru  # Optional group ownership
  notify:
    - Start sonarr

# Run Sonarr docker-compose up
- name: Run Sonarr docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ sonarr_compose_dir }}"
    files:
      - "{{ sonarr_compose_path }}"
    state: present
