---
- name: Ensure jellyseerr directories exist with proper permissions
  file:
    path: "{{ jellyseerr_compose_dir }}"
    state: directory
    mode: "0755"
    owner: "catguru"
    group: "catguru"
    recurse: true
  loop:
    - { path: "{{ jellyseerr_config_dir }}" }
    - { path: "{{ jellyseerr_data_dir }}" }

- name: Deploy jellyseerr Docker Compose file
  template:
    src: jellyseerr-compose.yml.j2
    dest: "{{ jellyseerr_compose_path }}"
  notify: 
    - Restart jellyseerr

- name: Launch jellyseerr using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ jellyseerr_compose_dir }}"
    files:
      - "{{ jellyseerr_compose_path }}"
    state: present
