---
- name: Download Tailscale GPG Key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: '0644'

- name: Add Tailscale repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/tailscale.list
    content: |
      deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ tailscale_ubuntu_release }} main

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present

- name: Log in to Tailscale using auth key
  command: "tailscale up --authkey={{ tailscale_authkey }}"
  register: tailscale_output
  changed_when: "'Success.' in tailscale_output.stdout or 'Logged in' in tailscale_output.stdout"
  failed_when: tailscale_output.rc != 0 and 'already logged in' not in tailscale_output.stderr