---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: catguru
    group: catguru
  loop:
    - "{{ radarr_compose_dir }}"
    - "{{ radarr_config_dir }}"
    - "{{ key_dir }}"  # Ensure the global key directory exists

- name: Copy the API key generation script to the target machine
  ansible.builtin.copy:
    src: "roles/config/api_gen/generate_api_key.py"
    dest: "/opt/api_gen/generate_api_key.py"
    mode: '0755'

- name: Generate Radarr API key
  command: >
    python3 /opt/api_gen/generate_api_key.py
    radarr
    "{{ key_dir }}"
  register: radarr_key_output
  changed_when: "'API key saved' in radarr_key_output.stdout"

- name: Debug Radarr API key generation output
  debug:
    var: radarr_key_output.stdout

- name: Deploy Radarr Docker Compose file
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "{{ radarr_compose_path }}"
    mode: '0755'
    owner: catguru
    group: catguru
  notify:
    - Restart Radarr

- name: Launch Radarr using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ radarr_compose_dir }}"
    files:
      - "{{ radarr_compose_path }}"
    state: present
