services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    network_mode: 'host'
    volumes:
      - /home/catguru/Documents/Docker/Configs/Jellyfin:/config
      - /home/catguru/Documents/Docker/Cache/Jellyfin:/cache
      - type: bind
        source: /media/catguru/709d2d4a-ba00-44c8-8b16-b430f9f03fd1/Media
        target: /Media
    restart: 'unless-stopped'
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      
  speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - /path/to/data:/config
        environment:
            - TZ=Europe/London
            - PGID=0
            - PUID=0
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/London
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /path/to/appdata/config:/app/config
    restart: unless-stopped
    
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr
    restart: unless-stopped
    ports:
        - 90:80
    volumes:
        - /home/catguru/Documents/Docker/Configs/Organizr:/config
    environment:
        - fpm=true #true or false | using true will provide better performance
        - branch=v2-master #v2-master or #v2-develop
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
    
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true   
    environment:
      - VPN_USERNAME=
      - VPN_PASSWORD=
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT_ENV=1239
      - INCOMING_PORT_ENV=8999
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.1.0/24 #adjust this to YOUR network settings
      - NAME_SERVERS=1.1.1.1,1.0.0.1 #you can use whatever DNS provider you want
    ports:
      - 1239:1239
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - /home/catguru/Documents/Docker/Configs/QBittorrentVPN:/config
      - /media/catguru/709d2d4a-ba00-44c8-8b16-b430f9f03fd1/Media/Downloading:/downloads
      - /etc/timezone:/etc/timezone:ro #This is for TimeZone
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/catguru/Documents/Docker/Configs/Prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /home/catguru/Documents/Docker/Configs/Radarr:/config
      - /media/catguru/709d2d4a-ba00-44c8-8b16-b430f9f03fd1/Media/Downloading:/downloads
      - /media/catguru/709d2d4a-ba00-44c8-8b16-b430f9f03fd1/Media/Movies:/Movies
    ports:
      - 7878:7878
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - /home/catguru/Documents/Docker/Configs/Sonarr:/config
      - /media/catguru/709d2d4a-ba00-44c8-8b16-b430f9f03fd1/Media/Downloading:/Downloads
      - /media/catguru/709d2d4a-ba00-44c8-8b16-b430f9f03fd1/Media/Shows:/Shows
      - /media/catguru/709d2d4a-ba00-44c8-8b16-b430f9f03fd1/Media/Anime:/Anime
    ports:
      - 8989:8989
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /media/catguru/709d2d4a-ba00-44c8-8b16-b430f9f03fd1/Media/Audiobooks:/audiobooks
      - /media/catguru/709d2d4a-ba00-44c8-8b16-b430f9f03fd1/Media/Podcasts:/podcasts
      - /home/catguru/Documents/Docker/Configs/Audiobookshelf:/config
      - /home/catguru/Documents/Docker/Cache/Audiobookshelf:/metadata
    environment:
      - TZ=Europe/London

## System Monitoring
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    ports:
      - 3000:3000
    restart: unless-stopped
