---
- name: Install required Ansible Galaxy collections and roles
  hosts: localhost
  tasks:
    - name: Install collections and roles from requirements.yml
      ansible.builtin.command:
        cmd: ansible-galaxy install -r ./requirements.yml
      changed_when: false

- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Include upgrade
      ansible.builtin.include_role:
        name: upgrade

- name: Check and install Docker
  hosts: all
  become: true
  roles:
    - docker_check

- name: Deploy applications using Docker
  hosts: all
  become: true
  roles:
#    - install/amp_install_role
    - install/tailscale_install
    - deploy/starr/radarr_deploy
    - deploy/starr/sonarr_deploy
    - deploy/starr/prowlarr_deploy
    - deploy/starr/jellyseerr_deploy
    - deploy/starr/lidarr_deploy
    - deploy/starr/recyclarr_deploy
    - deploy/media/jellyfin_deploy
    - deploy/media/qbittorrentvpn_deploy
    - deploy/media/audiobookshelf_deploy
    - deploy/media/jfa-go_deploy
    - deploy/utils/speedtest_tracker_deploy
 #   - deploy/utils/organizr_deploy
 #   - deploy/utils/portainer_deploy
