---
# Check if Docker service is running
- name: Check if Docker service is running
  ansible.builtin.service_facts:
  when: not docker_installed  # Skip if Docker is already installed

# Ensure Docker service is running
- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: not docker_installed  # Skip if Docker is already installed
  
- name: Ensure Bazarr directories exist with proper permissions
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
    owner: "root"
    group: "root"
  loop:
    - { path: "{{ bazarr_config_dir }}" }
    - { path: "{{ bazarr_data_dir }}" }
    - "{{ key_dir }}"             # Global directory for storing API keys
    - "{{ keygen_location }}"     # Directory for the API key generation script

# Check if the API key generation script already exists on the target machine
- name: Check if the API key generation script already exists
  ansible.builtin.stat:
    path: "{{ keygen_location }}/generate_api_key.py"  # Path to the script
  register: api_gen_script_stat  # Register the result to check if the file exists

# Copy the API key generation script to the target machine if it doesn't already exist
- name: Copy the API key generation script to the target machine (if not already present)
  ansible.builtin.copy:
    src: "roles/config/api_gen/generate_api_key.py"  # Source path of the script
    dest: "{{ keygen_location }}/generate_api_key.py"  # Destination path on the target machine
    mode: "{{ default_mode }}"                       # Use the global default mode variable
  when: not api_gen_script_stat.stat.exists          # Only copy if the script doesn't exist

# Check if the Bazarr API key file already exists
- name: Check if Bazarr API key already exists
  ansible.builtin.stat:
    path: "{{ key_dir }}/bazarr_api.key"  # Path to the Bazarr API key file
  register: bazarr_api_key_stat           # Register the result to check if the file exists

# Generate a new Bazarr API key if it doesn't already exist
- name: Generate Bazarr API key
  command: >
    python3 {{ keygen_location }}/generate_api_key.py  
    bazarr                                             
    "{{ key_dir }}"                                    
  register: bazarr_key_output                         # Register the output of the command
  changed_when: "'API key saved' in bazarr_key_output.stdout"  # Mark as changed if the key was saved
  when: not bazarr_api_key_stat.stat.exists           # Only run if the API key file doesn't exist

# Fetch the Bazarr API key from the remote machine to the control node
- name: Fetch Bazarr API key from the remote machine to the control node
  ansible.builtin.fetch:
    src: "{{ key_dir }}/bazarr_api.key"  # Path to the API key file on the remote machine
    dest: "./api/bazarr_api.key"            # Destination path on the control node
    flat: yes                           # Save the file directly to the specified path

# Deploy the Bazarr Docker Compose file using a template
- name: Deploy Bazarr Docker Compose file
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"  # Source template file
    dest: "{{ bazarr_compose_path }}"        # Destination path for the Docker Compose file
    mode: "{{ default_mode }}"               # Use the global default mode variable
    owner: "{{ bazarr_owner }}"              # Use the Bazarr-specific owner variable
    group: "{{ bazarr_group }}"              # Use the Bazarr-specific group variable
  notify:
    - Start Bazarr  # Notify the handler to restart Bazarr if the file changes

- name: Launch Bazarr using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ bazarr_compose_dir }}"
    files:
      - "{{ bazarr_compose_path }}"
    state: started