---
lidarr_config_dir: "{{ config_base_dir }}/lidarr"
lidarr_data_dir: "{{ lidarr_config_dir }}/data"
lidarr_compose_dir: "{{ compose_base_dir }}/lidarr"
lidarr_compose_path: "{{ lidarr_compose_dir }}/docker-compose.yml"
# Owner and group for Lidarr files and directories
lidarr_owner: "{{ default_owner }}"  # Use the global default owner variable
lidarr_group: "{{ default_group }}"  # Use the global default group variable