---
# Check if Docker service is running
- name: Check if Docker service is running
  ansible.builtin.service_facts:
  when: not docker_installed  # Skip if Docker is already installed

# Ensure Docker service is running
- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: not docker_installed  # Skip if Docker is already installed

- name: Setup Portainer directory
  ansible.builtin.file:
    path: "{{ portainer_compose_dir }}"
    state: directory
    mode: '0755'
    owner: catguru
    group: catguru

- name: Deploy Portainer using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "{{ portainer_compose_path }}"
    mode: '0755'
    owner: catguru
    group: catguru
  notify:
    - Start Portainer

- name: Run Portainer docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_compose_dir }}"
    files:
      - "{{ portainer_compose_path }}"
    state: present
